addons:
  postgresql: 11.2
after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - sudo apt-get update
  - sudo apt-get --yes remove postgresql\*
  - sudo apt-get install -y postgresql-11 postgresql-client-11
  - sudo cp /etc/postgresql/{9.6,11}/main/pg_hba.conf
  - sudo service postgresql restart 11
  - gem update --system
  - gem install bundler
before_script:
  - psql --version
  - psql -c 'CREATE DATABASE to_do_task_db;' -U postgres
  - psql -c 'CREATE ROLE travis SUPERUSER LOGIN CREATEDB;' -U postgres
  - cp config/database.yml.travis config/database.yml
dist: trusty
language: ruby
rvm:
  - 2.6.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec