addons:
  postgresql: 11.2
after_success:
  - bundle exec codeclimate-test-reporter
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database to_do_task_db;' -U postgres
dist: trusty
language: ruby
rvm:
  - 2.6.3
script:
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec